### ISSUE TITLE
Allow Select Parameter

### ISSUE THREAD

**Issue by kornpow** [py-actions/flake8#144]
For example:
`flake8 --ignore F401,F541,F811,F841,E,W --select E999 --max-line-length 100 .`

I want ignore all E rules, except for what is shown in select

**Comment by chrissimpkins** [comment]
Possible to give this a shot with the `args` definition in your configuration?  

https://github.com/py-actions/flake8#args

The intent is to support any argument that you can use with flake8.  So, I think that you should be able to configure it with the current release of the Action.  

But this doesn't fully get at your issue as I understand. We can certainly consider an explicit definition for this argument similar to the `exclude` and `ignore` inputs.  Do you feel that this is used commonly and warrants its own input field so that it can be used with the ignore field?

**Comment by kornpow** [comment]
Im sorry, I mustve glossed over that while reading the docs! `args` worked for me

**Comment by chrissimpkins** [comment]
Great!  Let me know if you run into any issues.
